language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - pip install PyYAML
    - pip install codecov
    - pip install schema
    - pip install python-magic

script:
    - make
    - ./test/run-tests.sh

after_success:
    - codecov
